apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  namespace: jenkins
  labels:
    app: hellp
spec:
  selector:
    matchLabels:
      app: hellp
      tier: web
  template:
    metadata:
      labels:
        app: hellp
        tier: web
    spec:
      containers:
      - name: hellp-app
        image: asia-south1-docker.pkg.dev/cloudside-academy/jenkins/hellp-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
